@PodiumdAdapter.Web_HostAddress = http://localhost:56090
@ContactmomentenRoot = {{PodiumdAdapter.Web_HostAddress}}/contactmomenten/api/v1
@KlantenRoot = {{PodiumdAdapter.Web_HostAddress}}/klanten/api/v1
@ZrcRoot = {{PodiumdAdapter.Web_HostAddress}}/zaken/api/v1
@ZtcRoot = {{PodiumdAdapter.Web_HostAddress}}/catalogi/api/v1


GET {{ContactmomentenRoot}}/contactmomenten?expand=objectcontactmomenten&klant={{KlantenRoot}}/klanten/83047d24-a213-4fc3-9878-367ffe06988e
Accept: application/json

###


GET {{ContactmomentenRoot}}/contactmomenten?object={{ZrcRoot}}/zaken/f54736d7-dafb-4e15-8650-3ebf870f3cba
Accept: application/json

###



POST {{ContactmomentenRoot}}/contactmomenten
Accept: application/json
Content-Type: application/json

{
    "bronorganisatie": "123",
    "url": "{{ContactmomentenRoot}}/contactmomenten/123",
    "tekst": "ik heb een vraag",
    "type": "Melding",
    "kanaal": "Internet"
}

###

GET {{ContactmomentenRoot}}/contactmomenten/c85c9545-454a-4b0b-abc1-f85977fdfde3

###

GET {{ContactmomentenRoot}}/klantcontactmomenten?klant={{KlantenRoot}}/klanten/3f4b8d6d-07f0-4d74-a3e1-e3e58e76eecb

###

GET {{ContactmomentenRoot}}/klantcontactmomenten?contactmoment={{ContactmomentenRoot}}/contactmomenten/4970067a-e0b8-40c0-b20a-f4b3c3947866
// 

###


GET {{ContactmomentenRoot}}/objectcontactmomenten?contactmoment={{ContactmomentenRoot}}/contactmomenten/1415127b-e969-42f4-9abd-fd1a22fc48bc

###

GET {{ContactmomentenRoot}}/objectcontactmomenten?object=http://localhost:56090/zaken/api/v1/zaken/f54736d7-dafb-4e15-8650-3ebf870f3cba

###


GET {{KlantenRoot}}/klanten?subjectNatuurlijkPersoon__inpBsn=999994864

###

GET {{KlantenRoot}}/klanten/83047d24-a213-4fc3-9878-367ffe06988e

###


PATCH {{KlantenRoot}}/klanten/83047d24-a213-4fc3-9878-367ffe06988e
Accept: application/json
Content-Type: application/json

{

}
###


GET {{ZrcRoot}}/zaken?rol__betrokkeneIdentificatie__natuurlijkPersoon__inpBsn=103226564

###

GET {{ZrcRoot}}/zaken/f54736d7-dafb-4e15-8650-3ebf870f3cba

###


GET {{ZtcRoot}}/zaaktypen

###