#
#
# To use this file disable 
# builder.Services.AddAuth(builder.Configuration); 
# in program.cs
#
#

@PodiumdAdapter_Web_HostAddress = http://localhost:5115
@ContactmomentenRoot = {{PodiumdAdapter_Web_HostAddress}}/contactmomenten/api/v1
@KlantenRoot = {{PodiumdAdapter_Web_HostAddress}}/klanten/api/v1
@ZrcRoot = {{PodiumdAdapter_Web_HostAddress}}/zaken/api/v1
@ZtcRoot = {{PodiumdAdapter_Web_HostAddress}}/catalogi/api/v1
@DrcRoot = {{PodiumdAdapter_Web_HostAddress}}/documenten/api/v1
@ObjectenRoot = {{PodiumdAdapter_Web_HostAddress}}/api/v2
@InterneTaakType = https://objecttypenpodiumd.dev.kiss-demo.nl/api/v2/objecttypes/1df73259-1a58-4180-bf98-598eefc184d4
@AfdelingenType = https://objecttypenpodiumd.dev.kiss-demo.nl/api/v2/objecttypes/ec65c0be-5e8d-4b72-b07f-7c4f78c84a18
@GroepenType = https://objecttypenpodiumd.dev.kiss-demo.nl/api/v2/objecttypes/8b9d6bf9-7b5a-4c38-ad10-f37cd1e81a8f
@SmoelenboekType = https://objecttypenpodiumd.dev.kiss-demo.nl/api/v2/objecttypes/748dd17b-2eb6-4084-95f0-a9040e27dced


GET {{ContactmomentenRoot}}/contactmomenten?expand=objectcontactmomenten&klant={{KlantenRoot}}/klanten/83047d24-a213-4fc3-9878-367ffe06988e
Accept: application/json

###


GET {{ContactmomentenRoot}}/contactmomenten?object={{ZrcRoot}}/zaken/f54736d7-dafb-4e15-8650-3ebf870f3cba
Accept: application/json

###



POST {{ContactmomentenRoot}}/contactmomenten
Accept: application/json
Content-Type: application/json

{
    "bronorganisatie": "123",
    "url": "{{ContactmomentenRoot}}/contactmomenten/123",
    "tekst": "dit is tekst",
    "vraag": "dit is vraag",
    "specifiekevraag": "dit is specifiekevraag",
    "type": "Melding",
    "kanaal": "e-mail"
}

###

GET {{ContactmomentenRoot}}/contactmomenten/16242f8a-ddc3-4f4f-8dca-a4781d40a84d

###

GET {{ContactmomentenRoot}}/klantcontactmomenten?klant={{KlantenRoot}}/klanten/3f4b8d6d-07f0-4d74-a3e1-e3e58e76eecb

###

GET {{ContactmomentenRoot}}/klantcontactmomenten?contactmoment={{ContactmomentenRoot}}/contactmomenten/4970067a-e0b8-40c0-b20a-f4b3c3947866
// 

###


GET {{ContactmomentenRoot}}/objectcontactmomenten?contactmoment={{ContactmomentenRoot}}/contactmomenten/1415127b-e969-42f4-9abd-fd1a22fc48bc

###

GET {{ContactmomentenRoot}}/objectcontactmomenten?object=http://localhost:56090/zaken/api/v1/zaken/f54736d7-dafb-4e15-8650-3ebf870f3cba

###


GET {{KlantenRoot}}/klanten?subjectNatuurlijkPersoon__inpBsn=999994864

###

GET {{KlantenRoot}}/klanten/83047d24-a213-4fc3-9878-367ffe06988e

###


PATCH {{KlantenRoot}}/klanten/83047d24-a213-4fc3-9878-367ffe06988e
Accept: application/json
Content-Type: application/json

{

}
###


GET {{ZrcRoot}}/zaken?rol__betrokkeneIdentificatie__natuurlijkPersoon__inpBsn=103226564

###

GET {{ZrcRoot}}/zaken/f54736d7-dafb-4e15-8650-3ebf870f3cba

###


GET {{ZtcRoot}}/zaaktypen

###

GET {{DrcRoot}}/enkelvoudiginformatieobjecten/4de76083-1fce-4852-876a-c833904d55a1/download

###


# https://podiumdcontact.dev.kiss-demo.nl/api/documenten/documenten/api/v1/enkelvoudiginformatieobjecten/4de76083-1fce-4852-876a-c833904d55a1
###

POST {{ObjectenRoot}}/objects
Accept: application/json
Content-Type: application/json

{
      "type": "{{InterneTaakType}}",
      "record": {
        "typeVersion": 1,
        "data": {
          "actor": null,
          "status": "nieuw",
          "betrokkene": {
            "rol": "klant",
            "klant": "http://localhost:56090/klanten/api/v1/klanten/83047d24-a213-4fc3-9878-367ffe06988e",
            "digitaleAdressen": [
              {
                "adres": "n.simon@rotterdam.nl",
                "omschrijving": "e-mailadres",
                "soortDigitaalAdres": "email"
              }
            ]
          },
          "toelichting": null,
          "contactmoment": "http://localhost:56090/contactmomenten/api/v1/contactmomenten/4970067a-e0b8-40c0-b20a-f4b3c3947866",
          "registratiedatum": "2021-03-08T09:43:47+01:00",
          "medewerkerIdentificatie": {
            "identificatie": "ESUITE_FG_LOKET",
            "achternaam": "Het digitale loket"
          }
        }
      }
    }

###

GET {{ObjectenRoot}}/objects?type={{InterneTaakType}}&data_attrs=betrokkene__klant__exact__{{KlantenRoot}}/klanten/83047d24-a213-4fc3-9878-367ffe06988e
Accept: application/json

###

          
GET {{ObjectenRoot}}/objects?type={{AfdelingenType}}
Accept: application/json

###

POST {{ContactmomentenRoot}}/contactmomenten
Accept: application/json
Content-Type: application/json   

{
    "actor": {
        "identificatie": "PUBL_HV_ADM",
        "naam": "groep:Administratie handhavingsverzoek",
        "soortActor": "organisatorische eenheid"
    },
    "betrokkene": {
        "digitaleAdressen": [
            {
                "adres": "0612345678",
                "omschrijving": "telefoonnummer",
                "soortDigitaalAdres": "telefoonnummer"
            }
        ],
        "persoonsnaam": {
        },
        "rol": "klant"
    },
    "bronorganisatie": "999990639",
    "einddatum": "2024-02-14T13:59:12.010Z",
    "gespreksresultaat": "Contactverzoek gemaakt",
    "initiatiefnemer": "klant",
    "kanaal": "Twitter",
    "medewerker": "sdfdsf",
    "medewerkerIdentificatie": {
        "achternaam": "Cornelissen",
        "identificatie": "Felix@icatt.nl",
        "voorletters": "Felix",
        "voorvoegselAchternaam": "sdfsdf"
    },
    "onderwerpLinks": [
    ],
    "registratiedatum": "2024-02-14T13:59:12.010Z",
    "specifiekevraag": "specifieke vraag",
    "startdatum": "2024-02-14T13:50:39.152Z",
    "status": "te verwerken",
    "tekst": "notitie",
    "toelichting": "notitie 14 feb 2:55",
    "verantwoordelijkeAfdeling": "afdeling:Algemeen",
    "voorkeurskanaal": "sdfsdf",
    "voorkeurstaal": "dsfsdf"
}

###       


GET {{ObjectenRoot}}/objects?type={{SmoelenboekType}}
Accept: application/json

  ###